server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 470674697304-scpnv9lgh8gjj5bfk398ldpoelorr8j9.apps.googleusercontent.com
            client-secret: cfZHy8ioQ3Atpm5qGryE_cVu
            scope:
              - email
              - profile
          facebook:
            client-id: 254021449688819
            client-secret: 7ce66147ba4f6ebb71045f3427c647c5
            scope:
              - email
              - public_profile
          naver:
            client-id: HlUG2mSsefhKot4fpPrQ
            client-secret: gsKha0PEjB
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider: # 등록안된 oauth provider 등록 *4칸뒤로
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 key값으로 naver가 리턴해줌.
